import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface Activity {
  time?: string;
  description: string;
}

export interface Trip {
  _id: string;
  destination: string;
  days: number;
  budgetType: string;
  aiProvider?: "gemini" | "fallback";

  itinerary: {
    day: number;
    activities: (string | Activity)[];
  }[];

  budgetBreakdown: {
    flights: number;
    accommodation: number;
    food: number;
    activities: number;
    total: number;
  };

  hotels: {
    name: string;
    type: string;
  }[];

  packingList: {
    item: string;
    packed: boolean;
    addedByUser: boolean;
  }[];
}

const PRIMARY: [number, number, number] = [37, 99, 235];
const DARK: [number, number, number] = [30, 41, 59];
const LIGHT: [number, number, number] = [100, 116, 139];

const LEFT_MARGIN = 18;
const PAGE_HEIGHT = 297;
const BOTTOM_MARGIN = 20;

function addSectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.6);
  doc.line(LEFT_MARGIN, y - 2, 192, y - 2);

  doc.setTextColor(...PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);

  doc.text(title, LEFT_MARGIN, y);

  doc.setTextColor(...DARK);

  return y + 8;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();

  for (let page = 1; page <= pages; page++) {
    doc.setPage(page);

    doc.setDrawColor(220);

    doc.line(LEFT_MARGIN, PAGE_HEIGHT - 12, 192, PAGE_HEIGHT - 12);

    doc.setFontSize(10);
    doc.setTextColor(...LIGHT);

    doc.text("Generated by TripPilot", LEFT_MARGIN, PAGE_HEIGHT - 6);

    doc.text(`Page ${page} of ${pages}`, 192, PAGE_HEIGHT - 6, {
      align: "right",
    });
  }
}

function ensureSpace(doc: jsPDF, y: number, needed = 30) {
  if (y + needed > PAGE_HEIGHT - BOTTOM_MARGIN) {
    doc.addPage();
    return 20;
  }

  return y;
}

export function exportTripAsPDF(trip: Trip) {
  const doc = new jsPDF();

  let y = 22;

  // ==========================
  // Title
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(...PRIMARY);

  doc.text("TripPilot", 105, y, {
    align: "center",
  });

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...LIGHT);

  doc.text("AI Powered Travel Planner", 105, y, {
    align: "center",
  });

  y += 10;

  doc.setDrawColor(...PRIMARY);
  doc.line(40, y, 170, y);

  y += 15;

  // ==========================
  // Trip Summary
  // ==========================

  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);

  doc.text(trip.destination, LEFT_MARGIN, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Duration: ${trip.days} Days`, LEFT_MARGIN, y);

  y += 7;

  doc.text(`Budget: ${trip.budgetType}`, LEFT_MARGIN, y);

  y += 7;

  doc.text(
    `AI Provider: ${
      trip.aiProvider === "gemini" ? "Google Gemini" : "Fallback Generator"
    }`,
    LEFT_MARGIN,
    y,
  );

  y += 7;

  doc.text(`Generated: ${new Date().toLocaleString()}`, LEFT_MARGIN, y);

  y += 12;

  // ==========================
  // Itinerary
  // ==========================

  y = addSectionTitle(doc, "ITINERARY", y);

  doc.setFontSize(11);

  for (const day of trip.itinerary) {
    y = ensureSpace(doc, y, 45);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY);

    doc.text(`Day ${day.day}`, LEFT_MARGIN, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);

    for (const activity of day.activities) {
      y = ensureSpace(doc, y, 12);

      if (typeof activity === "string") {
        const lines = doc.splitTextToSize(`• ${activity}`, 165);

        doc.text(lines, LEFT_MARGIN + 4, y);

        y += lines.length * 6;
      } else {
        const text = activity.time
          ? `${activity.time}   ${activity.description}`
          : activity.description;

        const lines = doc.splitTextToSize(`• ${text}`, 165);

        doc.text(lines, LEFT_MARGIN + 4, y);

        y += lines.length * 6;
      }
    }

    y += 6;
  }

  // ==========================
  // Budget Breakdown
  // ==========================

  y = ensureSpace(doc, y, 35);

  y = addSectionTitle(doc, "BUDGET BREAKDOWN", y);

  autoTable(doc, {
    startY: y,

    head: [["Category", "Estimated Cost"]],

    body: [
      ["Flights", `$${trip.budgetBreakdown.flights}`],
      ["Accommodation", `$${trip.budgetBreakdown.accommodation}`],
      ["Food", `$${trip.budgetBreakdown.food}`],
      ["Activities", `$${trip.budgetBreakdown.activities}`],
      ["Total", `$${trip.budgetBreakdown.total}`],
    ],

    headStyles: {
      fillColor: PRIMARY,
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },

    styles: {
      fontSize: 11,
      cellPadding: 4,
    },

    margin: {
      left: LEFT_MARGIN,
      right: LEFT_MARGIN,
    },
  });

  y =
    (
      doc as jsPDF & {
        lastAutoTable: { finalY: number };
      }
    ).lastAutoTable.finalY + 12;

  // ==========================
  // Hotels
  // ==========================

  y = ensureSpace(doc, y, 45);

  y = addSectionTitle(doc, "RECOMMENDED HOTELS", y);

  autoTable(doc, {
    startY: y,

    head: [["Hotel", "Type"]],

    body: trip.hotels.map((hotel) => [hotel.name, hotel.type]),

    headStyles: {
      fillColor: PRIMARY,
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },

    styles: {
      fontSize: 11,
      cellPadding: 4,
    },

    margin: {
      left: LEFT_MARGIN,
      right: LEFT_MARGIN,
    },
  });

  y =
    (
      doc as jsPDF & {
        lastAutoTable: { finalY: number };
      }
    ).lastAutoTable.finalY + 12;

  // ==========================
  // Packing Checklist
  // ==========================

  y = ensureSpace(doc, y, 50);

  y = addSectionTitle(doc, "PACKING CHECKLIST", y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...DARK);

  const packedItems = trip.packingList.filter((item) => item.packed).length;

  for (const item of trip.packingList) {
    y = ensureSpace(doc, y, 10);

    const checkbox = item.packed ? "[X]" : "[ ]";

    doc.text(`${checkbox} ${item.item}`, LEFT_MARGIN + 2, y);

    y += 7;
  }

  y += 5;

  y = ensureSpace(doc, y, 20);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...PRIMARY);

  const percentage =
    trip.packingList.length === 0
      ? 0
      : Math.round((packedItems / trip.packingList.length) * 100);

  doc.text(
    `Packing Progress: ${packedItems}/${trip.packingList.length} Items Packed (${percentage}%)`,
    LEFT_MARGIN,
    y,
  );

  y += 10;

  doc.setDrawColor(220);

  doc.line(LEFT_MARGIN, y, 192, y);

  addFooter(doc);

  doc.save(`${trip.destination.replace(/\s+/g, "-")}-Trip.pdf`);
}
